// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBim3LtFVpc4ATD3Giqjb7hlE1mB_RpMYU',
    appId: '1:185466314004:web:d998fa87ae8bd92ab23601',
    messagingSenderId: '185466314004',
    projectId: 'aska-402d5',
    authDomain: 'aska-402d5.firebaseapp.com',
    storageBucket: 'aska-402d5.firebasestorage.app',
    measurementId: 'G-KG5G0QC3MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0NThOkzqcaqonxl6igZ3rWdjI7Hl5q68',
    appId: '1:185466314004:android:f3336c9b7a739e29b23601',
    messagingSenderId: '185466314004',
    projectId: 'aska-402d5',
    storageBucket: 'aska-402d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSC4Qjz6N06JCMG0qZWwbBiCXEM8-2WuU',
    appId: '1:185466314004:ios:4588b675c4bc8be3b23601',
    messagingSenderId: '185466314004',
    projectId: 'aska-402d5',
    storageBucket: 'aska-402d5.firebasestorage.app',
    iosBundleId: 'com.example.aska',
  );
}
